name: Build and Test Matrix Multiplication

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          

    - name: Clone submodules
      run: git submodule update --init --recursive 

    - name: Set timezone and DEBIAN_FRONTEND
      run: |
        echo "tzdata tzdata/Areas select Etc" | sudo debconf-set-selections
        echo "tzdata tzdata/Zones/Etc select UTC" | sudo debconf-set-selections
        export DEBIAN_FRONTEND=noninteractive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup libfuse3-dev uidmap tzdata

        
    - name: Cache Go
      id: go-cache
      uses: actions/cache@v2
      with:
        path: /usr/local/go
        key: ${{ runner.os }}-go-1.19.4
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: |
        wget https://dl.google.com/go/go1.19.4.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.19.4.linux-amd64.tar.gz
        echo 'PATH=/usr/local/go/bin:$PATH' >> $GITHUB_ENV
        source $GITHUB_ENV

    - name: Cache Singularity
      id: singularity-cache
      uses: actions/cache@v2
      with:
        path: /usr/local/singularity
        key: ${{ runner.os }}-singularity-4.1.3
        restore-keys: |
          ${{ runner.os }}-singularity-

    - name: Install Singularity
      if: steps.singularity-cache.outputs.cache-hit != 'true'
      run: |
        VERSION=4.1.3
        wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz
        tar -xzf singularity-ce-${VERSION}.tar.gz 
        cd singularity-ce-${VERSION} 
        ./mconfig 
        make -C builddir 
        sudo make -C builddir install
        sudo mv builddir/singularity /usr/local/singularity
    - name: Enable user namespaces
      run: |
        sudo sysctl -w kernel.unprivileged_userns_clone=1
        sudo sysctl -w user.max_user_namespaces=15000


    - name: Build Singularity image
      run: singularity build --fakeroot --notest --force matrix_multiplication.sif singularity.def
    - name: Run tests
      run: singularity test --fakeroot --writable matrix_multiplication.sif
