name: Build and Test Matrix Multiplication

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Install MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DMPI_C_COMPILER=mpicc -DMPI_CXX_COMPILER=mpicxx

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release

  Containerize_and_run:
    runs-on: ubuntu-latest

    env: # Or as an environment variable
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup libfuse3-dev uidmap tzdata wget

       # Install Go if not cached
      - name: Install Go
        uses: actions/setup-go@v5

      # Install Singularity if not cached
      - name: Cache Singularity
        uses: actions/cache/restore@v4
        id: cache-singularity
        with:
          path: |
            singularity-ce-4.1.3
          key: ${{ runner.os }}-singularity

      - name: Build Singularity
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce-4.1.3.tar.gz
          tar -xzf singularity-ce-4.1.3.tar.gz
          cd singularity-ce-4.1.3
          ./mconfig -b ./singularity_build
          make -C ./singularity_build
        
      - name: Save Singularity
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            singularity-ce-4.1.3
          key: ${{ runner.os }}-singularity

      - name: Install Singularity
        run: |
          cd singularity-ce-4.1.3
          sudo make -C singularity_build install

      - name: Build Singularity image
        run: singularity build --fakeroot --force matrix_multiplication.sif singularity.def

      - name: Install sshpass
        run: sudo apt-get install openssh-client

      - name: Transfer files
        run: |
          ssh-keygen -R login.g100.cineca.it
          sshpass -p ${SSH_KEY} scp -o StrictHostKeyChecking=no matrix_multiplication.txt a08trb64@login.g100.cineca.it:~
          sshpass -p ${SSH_KEY} scp -o StrictHostKeyChecking=no job.sh a08trb64@login.g100.cineca.it:~
