name: Build and Test Matrix Multiplication

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_Containerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
          
    - name: Clone submodules
      run: git submodule update --init --recursive 

    - name: Set timezone and DEBIAN_FRONTEND
      run: |
        echo "tzdata tzdata/Areas select Etc" | sudo debconf-set-selections
        echo "tzdata tzdata/Zones/Etc select UTC" | sudo debconf-set-selections
        export DEBIAN_FRONTEND=noninteractive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup libfuse3-dev uidmap tzdata wget

        
     # Cache Go installation
    - name: Cache Go
      id: go-cache
      uses: actions/cache@v2
      with:
        path: ~/.go
        key: ${{ runner.os }}-go-1.19.4
        restore-keys: |
          ${{ runner.os }}-go-

    # Install Go if not cached
    - name: Install Go
      if: steps.go-cache.outputs.cache-hit != 'true'
      run: |
        wget https://dl.google.com/go/go1.19.4.linux-amd64.tar.gz
        tar -C $HOME -xzf go1.19.4.linux-amd64.tar.gz
        echo 'export PATH=$HOME/go/bin:$PATH' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Set PATH Go
      if: steps.go-cache.outputs.cache-hit == 'true'
      run: |
        echo 'export PATH=$HOME/go/bin:$PATH' >> $HOME/.bashrc
        source $HOME/.bashrc
      
    # Cache Singularity installation
    - name: Cache Singularity
      id: singularity-cache
      uses: actions/cache@v2
      with:
        path: ~/.singularity
        key: ${{ runner.os }}-singularity-4.1.3
        restore-keys: |
          ${{ runner.os }}-singularity-

    # Install Singularity if not cached
    - name: Install Singularity
      if: steps.singularity-cache.outputs.cache-hit != 'true'
      run: |
        export VERSION=4.1.3
        wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce-4.1.3.tar.gz
        tar -xzf singularity-ce-${VERSION}.tar.gz
        cd singularity-ce-${VERSION}
        ./mconfig
        make -C builddir
        sudo make -C builddir install
        mkdir -p $HOME/.singularity/bin
        cp e /usr/local/bin/singularity $HOME/.singularity/bin/singularity
        echo 'export PATH=$HOME/.singularity/bin:$PATH' >> $HOME/.bashrc
        source $HOME/.bashrc
    - name: Set PATH Go
      if: steps.singularity-cache.outputs.cache-hit  == 'true'
      run: |
        echo 'export PATH=$HOME/.singularity/bin:$PATH' >> $HOME/.bashrc
        source $HOME/.bashrc

      

    - name: Enable user namespaces
      run: |
        sudo sysctl -w kernel.unprivileged_userns_clone=1
        sudo sysctl -w user.max_user_namespaces=15000


    - name: Build Singularity image
      run: singularity build --fakeroot --notest --force matrix_multiplication.sif singularity.def


    - name: Run tests
      run: singularity test --fakeroot --writable matrix_multiplication.sif
